### ISSUE TITLE
Switch to mongodb 4.4.x

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#18198]
##### **Overview of the feature request**

Mongock now supports reactive driver: https://docs.mongock.io/v5/driver/mongodb-reactive/index.html
Thanks @dieppa

We can now remove the workaround created by @mishima with the update to spring-boot 2.6.x (use driver 4.2.3 instead of 4.4.x):
- generator: https://github.com/jhipster/jhipster-bom/pull/591
- bom: https://github.com/jhipster/jhipster-bom/pull/591

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by dieppa** [comment]
Hi @mraible, @osantana85 was able to reproduce it and we are looking at it

**Comment by mraible** [comment]
Thank you @dieppa!

**Comment by atomfrede** [comment]
Tracking it at jh lite too https://github.com/jhipster/jhipster-lite/issues/4067

**Comment by mraible** [comment]
@dieppa Do you have an update or issue we can track?

**Comment by dieppa** [comment]
@mraible https://github.com/mongock/mongock/issues/583

**Comment by dieppa** [comment]
@mraible , as you have probably already seen in this [Jhipster issue](https://github.com/jhipster/jhipster-lite/issues/4067), we have released the mongock runner for springboot 3 and driver for springdata v4. 

However I am looking again this ticket and I am wondering if what you need here is upgrading the reactive driver. Which, having build the foundation for the jdk7 modules mentioned above(springboot 3 runner and springdata 4 driver), it should be pretty straight forward.

Let me know if you need anything! 😃

**Comment by atomfrede** [comment]
I will have a look, I also think this is not related to springdata 4 and boot 3 as this is about boot 2. But the error looks the same.

**Comment by mraible** [comment]
I tried [the steps to upgrade to Mongock 5.1.7](https://github.com/jhipster/jhipster-lite/issues/4067#issuecomment-1293024524), followed by [these steps from above](https://github.com/jhipster/generator-jhipster/issues/18198#issuecomment-1286067850). I still get an error on startup:

```
2022-10-27T08:46:28.479+01:00  WARN 2694 --- [  restartedMain] onfigReactiveWebServerApplicationContext : Exception encountered during context 
initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name
'getBuilder' defined in class path resource [io/mongock/runner/springboot/config/MongockContext.class]: Unsatisfied dependency expressed through method 
'getBuilder' parameter 0: Error creating bean with name 'connectionDriver' defined in class path resource 
[io/mongock/driver/mongodb/springdata/v4/config/SpringDataMongoV4Context.class]: Unsatisfied dependency expressed through method 'connectionDriver' 
parameter 0: No qualifying bean of type 'org.springframework.data.mongodb.core.MongoTemplate' available: expected at least 1 bean which qualifies as 
autowire candidate. Dependency annotations: {}

2022-10-27T08:46:30.552+01:00 ERROR 2694 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : __***************************_APPLICATION 
FAILED TO START_***************************__Description:__Parameter 0 of method connectionDriver in 
io.mongock.driver.mongodb.springdata.v4.config.SpringDataMongoV4ContextBase required a bean of type 
'org.springframework.data.mongodb.core.MongoTemplate' that could not be found.___Action:__Consider defining a bean of type 
'org.springframework.data.mongodb.core.MongoTemplate' in your configuration._
```

If I add the following back in, it starts!

```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-mongodb</artifactId>
</dependency>
```

Commits:

- jhipster-bom: https://github.com/jhipster/jhipster-bom/pull/986/commits/540acec66d4109f1a21a4354b37215a5049aeff8
- generator-jhipster: https://github.com/jhipster/generator-jhipster/pull/19791/commits/5a2a59781d32fbb161eeb53420f95bb2275e81cd

**Comment by atomfrede** [comment]
The mongock driver has the dependency for spring set to `provided` so I think thats correct. Do I get it correct, this is indeed about boot 3 and not 2?

**Comment by mraible** [comment]
Yes, this is for Spring Boot 3.

**Comment by atomfrede** [comment]
Makes sense we don't do such an update for jh 7.x right now. Awesome, so everything looks good here?

**Comment by mraible** [comment]
@atomfrede I think so. We'll see what CI says.

**Comment by dieppa** [comment]
I am keeping an eye here to see how it progresses and in what I can help with 👀

**Comment by atomfrede** [comment]
@mraible Can we close this from your point of view?

**Comment by pascalgrimaud** [comment]
@atomfrede : approved
