### ISSUE TITLE
CORS Filter issue

### ISSUE THREAD

**Issue by ARAtIntBitTech** [jhipster/generator-jhipster#3237]
Created a simple JHipster app with OAuth2. Uncommented the CORS lines in the application.yml file to enable CORS. 

```
jhipster:
async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

cors: #By default CORS are not enabled. Uncomment to enable.
    allowed-origins: "*"
    allowed-methods: GET, PUT, POST, DELETE, OPTIONS
    allowed-headers: "*"
    exposed-headers:
    allow-credentials: true
    max-age: 1800
```

And in the "Webconfigurer"

```
@Bean
    public CorsFilter corsFilter() {
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        CorsConfiguration config = props.getCors();
        if (config.getAllowedOrigins() != null && !config.getAllowedOrigins().isEmpty()) {
            source.registerCorsConfiguration("/api/**", config);
            source.registerCorsConfiguration("/v2/api-docs", config);
            source.registerCorsConfiguration("/oauth/**", config);
        }
        return new CorsFilter(source);
    }

```

Soon after that, whenever I make the token request, I get the below error in the browser

`http://localhost:8080/oauth/token?username=admin&password=admin&grant_type=password&scope=read. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9090' is therefore not allowed access. The response had HTTP status code 401.`

JHipster Version(s)
v2.27.2

Browsers and Operating System
Ubuntu/Chrome

**Comment by cbornet** [comment]
We need your .yo-rc.json file as requested when you opened the issue

**Comment by jdubois** [comment]
Duplicate from #3233 - what's happening here?

**Comment by ARAtIntBitTech** [comment]
`{
  "generator-jhipster": {
    "baseName": "HelloWebServices",
    "packageName": "com.intbit.hello",
    "packageFolder": "com/intbit/hello",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "gulp",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "d91ebba1d3edfc07a6a44ab1ca798808d5ffc7d3",
    "testFrameworks": [
      "gatling"
    ]
  }
}`

**Comment by ARAtIntBitTech** [comment]
@jdubois  you requested me to create a new issue without cross posting messages, which I understood as sharing the SO link. So I wrote all the info that I could. Added the .yo-rc.json as well.

**Comment by jdubois** [comment]
Sorry I didn't see you were the same person!
What's happening with StackOverflow?

**Comment by ARAtIntBitTech** [comment]
@jdubois .. no problem at all. I didn't get any response on SO. Also, I have a feeling this is a JHipster issue. I created a new project and see the same problem there.

**Comment by jdubois** [comment]
Yes I agree this looks like a JHipster issue, I'm reopening this.

**Comment by cbornet** [comment]
@ARAtIntBitTech Does your request work non-cross-domain ? Can you post the curl request in this issue (in firefox: right click -> Copy as cURL) ?

**Comment by cbornet** [comment]
If there is a pre-flight request (OPTIONS), also post it.

**Comment by ARAtIntBitTech** [comment]
@cbornet  I have a sample project running at 9090. This makes the ajax call.

```
$http({
                    method: 'GET',
                    url: "http://localhost:8080/oauth/token?username=admin&password=admin&grant_type=password&scope=read",
                    headers: {
                        'Authorization' : 'Basic R09BVFdlYlNlcnZpY2VzYXBwOm15U2VjcmV0T0F1dGhTZWNyZXQ=',                        
                        'Content-Type': 'application/json'
                    }  
                }).success(function (data) {
                    alert(JSON.stringify(data));
                }).error(function (error) {
                    alert(JSON.stringify(error));
                });
```

And this is the response in the console of client (Chrome browser)

`XMLHttpRequest cannot load http://localhost:8080/oauth/token?username=admin&password=admin&grant_type=password&scope=read. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9090' is therefore not allowed access. The response had HTTP status code 401.`

When I do the same thing on command line. It works. Let me know if you need more info

```
$ curl -X POST --header "Authorization: Basic R09BVFdlYlNlcnZpY2VzYXBwOm15U2VjcmV0T0F1dGhTZWNyZXQ="  http://dev1.intbittech.com/goatwebservices-0.0.1-SNAPSHOT/oauth/token -H "Accept: application/json" -d "username=admin&password=admin&grant_type=password&scope=read"
{"access_token":"47ecbd43-1ca6-411e-8ac5-e3d1daad2213","token_type":"bearer","refresh_token":"0359d693-7035-40db-b2b0-70744ebb4ea1","expires_in":9309,"scope":"read"}
```

**Comment by cbornet** [comment]
Can you give the curl request that **exactly** matches the one from your browser (with all Host, Origin, Referer headers ...) ? You can get it from your browser developper tools

**Comment by ARAtIntBitTech** [comment]
Hope this helps. If this also doesn't help in troubleshooting, I have the env ready for testing. Feel free to mail me ar@intbittech.com. I can do a screenshare.

<img width="1236" alt="screen shot 2016-03-22 at 11 01 41 am" src="https://cloud.githubusercontent.com/assets/11681651/13956063/87212baa-f01d-11e5-8e74-67e0c21d73e2.png">

**Comment by cbornet** [comment]
Can you right-click on your OPTIONS request, select "Copy as cURL" then paste here ?

**Comment by ARAtIntBitTech** [comment]
Sorry, here you go

`curl 'http://localhost:8080/oauth/token?username=admin&password=admin&grant_type=password&scope=read' -X OPTIONS -H 'Host: localhost:8080' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Access-Control-Request-Method: POST' -H 'Access-Control-Request-Headers: authorization' -H 'origin: http://localhost:9090' -H 'Connection: keep-alive'`

**Comment by cbornet** [comment]
Actually, this is fixed on the master in commit https://github.com/jhipster/generator-jhipster/pull/2650/commits/34ff27f916e631f33a8e6d61c4da88ec6552923d
On v2.x, the OPTIONS were authorized for logged-in users but this is not enough: for CORS to work, the security for OPTIONS must be completely removed.

@ARAtIntBitTech can you test that it works for you by adding ```.antMatchers(HttpMethod.OPTIONS, "/**")``` to the ignored security like done [here](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/config/_SecurityConfiguration.java#L77) ?

@jdubois do we merge the fix on v2.x ?

**Comment by ARAtIntBitTech** [comment]
@cbornet  thank you for looking into this. But I already have that in the config "OAuth2ServerConfiguration"

```
 .and()
                .authorizeRequests()
                .antMatchers(HttpMethod.OPTIONS, "/**").permitAll()
                .antMatchers("/api/authenticate").permitAll()
                .antMatchers("/api/register").permitAll()
```

`curl 'http://localhost:8080/oauth/token?username=admin&password=admin&grant_type=password&scope=read' -X OPTIONS -H 'Host: localhost:8080' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Access-Control-Request-Method: POST' -H 'Access-Control-Request-Headers: authorization' -H 'origin: http://localhost:9090' -H 'Connection: keep-alive'`

I noticed that in the header of this request, it doesn't add the Basic token.

**Comment by cbornet** [comment]
As I said, the config in OAuth2ServerConfiguration is insufficient. Please try the fix in SecurityConfiguration.
It is normal that the Basic Token is removed in pre-flight request : they remove every custom headers and that is why you are not authorized.

**Comment by ARAtIntBitTech** [comment]
@cbornet sorry, misread your statement earlier. And thank you for clarifying my doubt. However, I added the line to ignore the options and it still doesn't work

```
@Override
    public void configure(WebSecurity web) throws Exception {
        web.ignoring()
        	.antMatchers(HttpMethod.OPTIONS, "/**")
            .antMatchers("/scripts/**/*.{js,html}")
            .antMatchers("/bower_components/**")
            .antMatchers("/i18n/**")
            .antMatchers("/assets/**")
            .antMatchers("/swagger-ui/index.html")
            .antMatchers("/api/register")
            .antMatchers("/api/activate")
            .antMatchers("/api/account/reset_password/init")
            .antMatchers("/api/account/reset_password/finish")
            .antMatchers("/test/**");
    }
```

Now it says 

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/oauth/token?username=admin&password=admin&grant_type=password&scope=read. (Reason: CORS header 'Access-Control-Allow-Origin' missing).`

Shouldn't the code automatically add the header `Access-Control-Allow-Origin` with the right value?

`curl 'http://localhost:8080/oauth/token?username=admin&password=admin&grant_type=password&scope=read' -X OPTIONS -H 'Host: localhost:8080' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Access-Control-Request-Method: POST' -H 'Access-Control-Request-Headers: authorization' -H 'origin: http://localhost:9090' -H 'Connection: keep-alive'`

**Comment by cbornet** [comment]
Strange: it works on my setup with your exact curl request. Can you add -v option to your curl command and paste the result here ?
This is the result to your curl command with -v on my computer
```
* Connected to localhost (127.0.0.1) port 8080 (#0)
> OPTIONS /oauth/token?username=admin&password=admin&grant_type=password&scope=read HTTP/1.1
> Accept-Encoding: deflate, gzip
> Host: localhost:8080
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
> Accept-Language: en-US,en;q=0.5
> Access-Control-Request-Method: POST
> Access-Control-Request-Headers: authorization
> origin: http://localhost:9090
> Connection: keep-alive
> 
< HTTP/1.1 200 OK
* Server Apache-Coyote/1.1 is not blacklisted
< Server: Apache-Coyote/1.1
< Access-Control-Allow-Origin: http://localhost:9090
< Vary: Origin
< Access-Control-Allow-Methods: GET,PUT,POST,DELETE,OPTIONS
< Access-Control-Allow-Headers: authorization
< Access-Control-Allow-Credentials: true
< Access-Control-Max-Age: 1800
< Content-Length: 0
< Date: Tue, 22 Mar 2016 19:32:34 GMT
< 
* Connection #0 to host localhost left intact
```

**Comment by cbornet** [comment]
Are you sure it is the OPTIONS pre-flight request that is now blocked and not the POST request ?

**Comment by ARAtIntBitTech** [comment]
Hey @cbornet  I just tested this out on my local system. Both the OPTIONS pre-flight request and POST worked. I received the access token Thanks!!!!!. 
But when I uploaded the war file on a server and executed the AJAX call from my local machine it shows an error. 403 forbidden.

This is the CURL from the browser
`curl 'https://dev1.intbittech.com/test/oauth/token?username=admin&password=admin&grant_type=password&scope=read' -H 'Host: dev1.intbittech.com' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Authorization: Basic R09BVFdlYlNlcnZpY2VzYXBwOm15U2VjcmV0T0F1dGhTZWNyZXQ=' -H 'Referer: http://localhost:9090/New/test.jsp' -H 'origin: http://localhost:9090' -H 'Connection: keep-alive' -H 'Content-Length: 0'`

But when I ran the same command from terminal, it works.

```
curl -v 'http://dev1.intbittech.com/test/oauth/token?username=admin&password=admin&grant_type=password&scope=read' -X OPTIONS -H 'Host: localhost:8080' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Access-Control-Request-Method: POST' -H 'Access-Control-Request-Headers: authorization' -H 'origin: http://localhost:9090' -H 'Connection: keep-alive' 
*   Trying 45.79.180.162...
* Connected to dev1.intbittech.com (45.79.180.162) port 80 (#0)
> OPTIONS /test/oauth/token?username=admin&password=admin&grant_type=password&scope=read HTTP/1.1
> Host: localhost:8080
> Accept-Encoding: deflate, gzip
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
> Accept-Language: en-US,en;q=0.5
> Access-Control-Request-Method: POST
> Access-Control-Request-Headers: authorization
> origin: http://localhost:9090
> Connection: keep-alive
> 
< HTTP/1.1 200 OK
< Server: nginx/1.6.2 (Ubuntu)
< Date: Tue, 22 Mar 2016 20:57:43 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< Access-Control-Allow-Origin: http://localhost:9090
< Vary: Origin
< Access-Control-Allow-Methods: GET,PUT,POST,DELETE,OPTIONS
< Access-Control-Allow-Headers: authorization
< Access-Control-Allow-Credentials: true
< Access-Control-Max-Age: 1800
< 
* Connection #0 to host dev1.intbittech.com left intact
```

**Comment by cbornet** [comment]
Does your browser attempt to send the POST ? Or is it blocked at the OPTIONS request ?

**Comment by cbornet** [comment]
Did you set withCredentials flag to true in your AJAX call ?

**Comment by ARAtIntBitTech** [comment]
@cbornet browser is able to send the OPTIONS and get a 200 back. But the POST request is blocked. I get a forbidden.

<img width="1233" alt="screen shot 2016-03-22 at 6 42 57 pm" src="https://cloud.githubusercontent.com/assets/11681651/13970374/b28dd7ac-f05e-11e5-9272-bb462c18f6d8.png">

And yes my ang js call includes withCredentials: true

`$http({
                    method: 'POST',
                    withCredentials: true,
                    url: "https://dev1.intbittech.com/goatwebservices-0.0.1-SNAPSHOT/oauth/token?username=admin&password=admin&grant_type=password&scope=read", 
                    headers: {
                        'Authorization' : 'Basic R09BVFdlYlNlcnZpY2VzYXBwOm15U2VjcmV0T0F1dGhTZWNyZXQ=',                        
                        'Content-Type': 'application/json'
                    }
                }).success(function (data) {
                    alert(JSON.stringify(data));
                }).error(function (error) {
                    alert(JSON.stringify(error));
                });`

Thank you so much for helping me with this. Appreciate your help. I am sure this will be very useful to many other folks.

**Comment by ARAtIntBitTech** [comment]
@cbornet any idea? I checked the cors config of my nginx server.

```
location / {
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#	   	dav_methods DELETE PUT;
#		auth_basic "Restricted";
#		auth_basic_user_file /etc/nginx/.htpasswd;

		if ($request_method = 'OPTIONS') {
        			add_header 'Access-Control-Allow-Origin' $http_origin;
        			#
        			# Om nom nom cookies
        			#
        			add_header 'Access-Control-Allow-Credentials' 'true';
        			add_header 'Access-Control-Allow-Methods' 'GET, DELETE, PUT, POST, OPTIONS';
        			#
            		#
                        # Custom headers and headers various browsers *should* be OK with but aren't
                        #
                        add_header 'Access-Control-Allow-Headers' 'Authorization,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
                        #
                        # Tell client that this pre-flight info is valid for 20 days
                        #
                        add_header 'Access-Control-Max-Age' 1728000;
                        add_header 'Content-Type' 'text/plain charset=UTF-8';
                        add_header 'Content-Length' 0;
                        return 204;
                }
                if ($request_method = 'POST') {
                        add_header 'Access-Control-Allow-Origin' '*';
                        add_header 'Access-Control-Allow-Credentials' 'true';
                        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
                        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
                }
                if ($request_method = 'GET') {
                        add_header 'Access-Control-Allow-Origin' '*';
                        add_header 'Access-Control-Allow-Credentials' 'true';
                        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
                        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
                }
	}
```

**Comment by cbornet** [comment]
Can you paste the curl -v of the POST request ?

**Comment by ARAtIntBitTech** [comment]
> curl 'http://dev1.intbittech.com/goatwebservices-0.0.1-SNAPSHOT/oauth/token?username=admin&password=admin&grant_type=password&scope=read' -H 'Host: dev1.intbittech.com' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Authorization: Basic R09BVFdlYlNlcnZpY2VzYXBwOm15U2VjcmV0T0F1dGhTZWNyZXQ=' -H 'Referer: http://localhost:9090/NewGoat/test.jsp' -H 'Origin: http://localhost:9090' -H 'Connection: keep-alive' -H 'Content-Length: 0'

**Comment by SyedIlyasAtIntBitTech** [comment]
@cbornet I was able to hit the oauth url from mozilla firefox and am getting the bearer token but it does not work in chrome.

`curl 'http://dev1.intbittech.com/goatwebservices-0.0.1-SNAPSHOT/oauth/token?username=admin&password=admin&grant_type=password&scope=read' -X POST -H 'Host: dev1.intbittech.com' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Authorization: Basic R09BVFdlYlNlcnZpY2VzYXBwOm15U2VjcmV0T0F1dGhTZWNyZXQ=' -H 'Referer: http://dev1.intbittech.com/NewGoatByIlyas/test.jsp'`

**Comment by cbornet** [comment]
Can you paste the curl command and response for Chrome then ? Don't forget to set -v option.
Also I see that you are setting the CORS headers in nginx and not in the jhipster app which is a possibility but note that it's not really a jhipster issue anymore...

**Comment by SyedIlyasAtIntBitTech** [comment]
@cbornet 

Curl command from chrome:
curl 'http://dev1.intbittech.com/goatwebservices-0.0.1-SNAPSHOT/oauth/token?username=admin&password=admin&grant_type=password&scope=read' -X POST -H 'Authorization: Basic R09BVFdlYlNlcnZpY2VzYXBwOm15U2VjcmV0T0F1dGhTZWNyZXQ=' -H 'Origin: http://dev1.intbittech.com' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36' -H 'Accept: application/json, text/plain, */*' -H 'Referer: http://dev1.intbittech.com/NewGoatByIlyas/test.jsp' -H 'Cookie: JSESSIONID=00D3CF44F1BD8596BD2D7C5788E9D611; NG_TRANSLATE_LANG_KEY=%22en%22; __utma=175206455.450546902.1451312585.1452772901.1452772901.1; __utmz=175206455.1452772901.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); _ga=GA1.2.450546902.1451312585' -H 'Connection: keep-alive' -H 'Content-Length: 0' --compressed

Response:
Failed to load resource: the server responded with a status of 403 (Forbidden)

We have set CORS in jhipster too, since it didn`t work we started doing random stuffs one of them was CORS in nginx, we have also done it in tomcat8...

**Comment by cbornet** [comment]
The request above is not cross-domain so it has nothing to do with CORS (I believe you don't even see any preflight OPTIONS request). This looks like some nginx or tomcat configuration issue and I don't think we can help much here. What I can say is that if I remove the Origin and Cookie headers, then the request is OK so there must be something related to that.
You should check in the logs which of your component rejected the  request (nginx, tomcat or spring) and if the request reaches jhipster what is in it and what is jhipster's answer.

**Comment by deepu105** [comment]
since this doesnt seem like a Jhipster issue Im closing this. Plz feel free to ask us to reopen if you think this an issue within jhipster

**Comment by cbornet** [comment]
There remains the question of backporting #2650 to v2.x branch.

**Comment by ARAtIntBitTech** [comment]
@cbornet  Could I PM you for some help(please)? I got past the login issue. All the other calls behind login have that problem now.

**Comment by cbornet** [comment]
Yes you can post your question on [gitter](https://gitter.im/jhipster/generator-jhipster)

**Comment by jvence** [comment]
I'm using microservice on jHipster 3 and using the generated war file to run the service and I am still experiencing this problem. I have enabled CORS on both the gateway and microservice but request through an app return: "Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://xxx' is therefore not allowed access. The response had HTTP status code 403."

I can hit the request directly from the browser.

**Comment by cbornet** [comment]
FYI, after proper setup, @ARAtIntBitTech was able to make the CORS work for him so this is probably not an issue with JHipster. You can PM me on gitter if you want and I'll try to help you. Making CORS work is really a pain....

**Comment by ganeshkrishnan1** [comment]
jvence above is correct. Your commit  34ff27f is for WebSecurity in jhipster-registry and I am not sure how that would affect microservice project or pre-flight requests to services in microservice project. 

I managed to fix this issue by creating new SecurityConfiguration for microservice project. The jhipster does not generate websecurity config for either gateway or microservice project.
