### ISSUE TITLE
Upgrade to Typescript 2.4.x

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#6051]
Please note that TS 2.4.x breaks our builds due to following issues (Actually this version of TS has better type inference and stricter type checks which surface some of the hidden issues in our code), hence we need to fix those as well

1.  RxJS has some issues https://github.com/ReactiveX/rxjs/issues/2539
2. Our entity component code has issues

**Comment by deepu105** [comment]
@pascalgrimaud I found something weird with our travis prod build while working on this issue.
https://travis-ci.org/jhipster/generator-jhipster/jobs/253976729#L3315
The build either failed or stalled but its reported as passed. Any idea?

**Comment by deepu105** [comment]
@pascalgrimaud not just one most of our recent prod builds are stalled at that point so technically we are never testing the prod AOT builds https://travis-ci.org/jhipster/generator-jhipster/jobs/253721138#L3322

**Comment by pascalgrimaud** [comment]
I will have a look tomorrow @deepu105

**Comment by deepu105** [comment]
@pascalgrimaud I think it might have something to do with the logging from the maven frontend plugin. The webpack part is written as ERROR instead of INFO
```
[ERROR]  10% building modules 1/4 modules 3 active .../main/webapp/content/scss/global.scssWarning: The 'no-use-before-declare' rule requires type infomation.
[INFO] 
[INFO] [at-loader] Using typescript@2.4.1 from typescript and "tsconfig.json" from /home/deepu/workspace/temp/jh4test/tsconfig-aot.json.
[INFO] 
24231ms building modules                                                                 
[ERROR] 47ms sealing
[ERROR] 0ms optimizing 
[ERROR] 0ms basic module optimization 
[ERROR] 217ms module optimization
[ERROR] 0ms advanced module optimization 
[ERROR] 21ms basic chunk optimization       
[ERROR] 0ms chunk optimization 
[ERROR] 2ms advanced chunk optimization 
[ERROR] 1ms module and chunk tree optimization 
[ERROR] 1ms chunk modules optimization 
[ERROR] 0ms advanced chunk modules optimization 
[ERROR] 10ms module reviving
[ERROR] 0ms module order optimization 
[ERROR] 12ms module id optimization
[ERROR] 3ms chunk reviving 
[ERROR] 1ms chunk order optimization 
[ERROR] 26ms chunk id optimization
[ERROR] 259ms hashing
[ERROR] 0ms module assets processing 
[ERROR] 473ms chunk assets processing
[ERROR] 210ms additional chunk assets processing
[ERROR] 0ms recording 
[ERROR] 17048ms additional asset processing
[ERROR] 0ms chunk asset optimization 
[INFO] 
[INFO] [at-loader] Checking started in a separate process...
[ERROR]  94% asset optimization(node:21575) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
[INFO] 
[INFO] [at-loader] Ok, 1.226 sec.
[INFO] MergetJsonsWebpackPlugin emit...
1658ms asset optimization
[ERROR] 169ms emitting
[INFO] Hash: e59624ce8336fa4c4454

```

**Comment by sendilkumarn** [comment]
@deepu105 The error is actually a warning. 
it shows error when we take an aot build but still the build passes. 

This has to be fixed 
 .../main/webapp/content/scss/global.scssWarning: The 'no-use-before-declare' rule requires type infomation.

guess it is an angular errror

**Comment by deepu105** [comment]
I have fixed it already but the behaviour is same look at latest builds


Thanks & Regards,
Deepu

**Comment by sendilkumarn** [comment]
what is the fix ?

**Comment by deepu105** [comment]
enabling type-check in lint look at my commit or typescript upgrade

**Comment by sendilkumarn** [comment]
adding type-check don't stop the warning. I am still seeing the warning 😞

**Comment by deepu105** [comment]
@sendilkumarn which warning are you talking about? Are you trying on latest master?

**Comment by sendilkumarn** [comment]
see the comment in the closed pull request :(
