### ISSUE TITLE
Migrate Elasticsearch + Cassandra tests to TestContainers

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#7000]
[TestContainers](https://www.testcontainers.org/) is a nice library that uses Docker to run databases during integration tests, by @rnorth

In the past, I've tried all my best to avoid it, as I'd rather used embedded databases, as it's faster/easier, but with our Spring Boot 2 migration, here is our current state:

- SQL databases -> no problem thanks to H2
- MongoDB -> no problem thanks to Flapdoodle's Embedded MongoDB (and that's incredible, when you think of it)
- Elasticsearch -> this is currently failing (ping @michael-wirth ). This is because Elastic is pushing very hard to suppress the use of an embedded MongoDB server, as they hope this will drive their sales numbers - this is of course very annoying for us.
- Cassandra -> this is basically the same issue as Elasticsearch, as the company has the same strategy. We had a hack with CassandraUnit to make it works, which looks OK locally, but fails on Travis.
- Couchbase -> they already use TestContainers as I guess @tchlyah didn't know we wanted to avoid it :-)

-> I think we should migrate to TestContainers for Elasticsearch & Cassandra (and keep Couchbase, of course). We can't fight against the projects, basically.

Then this forces everyone to have Docker running (a lot of our users are using Windows 7, so this will be annoying for them), both for tests (using TestContainers) and for development (using Docker Compose). But the more move on, the more we take for granted that Docker is up & running on the dev/test machines. WDYT?

**Comment by deepu105** [comment]
That sucks, It makes docker a mandatory dependency which is not nice :(
For Cassandra and couchbase its fine as usage is very less so only less
people affected but I guess elasticsearch is used more. But if we have no
other choice then we should do it


Thanks & Regards,
Deepu

**Comment by michael-wirth** [comment]
It would be nice to run embedded Elasticsearch, but at the  moment we have 2 dependency problems.
1. Elasticsearch requires log4j-core -> possible solution is to write an adapter for  https://github.com/elastic/elasticsearch/blob/v6.1.1/core/src/main/java/org/elasticsearch/common/logging/Loggers.java 
2. Gatling and Elasticsearch don't play together well as they require different io.netty libs

**Comment by jdubois** [comment]
Indeed, let me highlight the main issues here, as Docker would be mandatory:

- This is bad for people not using Docker, or being stuck on older Windows releases or on Mac (I don't know for Windows, but I guarantee you Docker 4 Mac sucks big time, I use it every day and it's slow, buggy, and requires a lot of RAM)
- It's slower than embedded databases, obviously
- This will fail on some CI systems, as you'll need Docker installed

Also, it looks like TestContainers requires a specific Docker setup: it won't run on my Mac as it says my DOCKER_HOST isn't configured - and of course my Mac is correctly configured, I've been using Docker every day for years.

-> maybe the solution would be to continue trying to have Elasticsearch run in embedded mode, even if at some point in the future this won't be possible anymore. At least we could have this for a couple of years, and then maybe Docker won't be an issue anymore - @michael-wirth do you think you could solve those dependency issues? Maybe Java 9 modules could help?

**Comment by PierreBesson** [comment]
@jdubois I think the problems you are having with testcontainer and docker for mac are caused because of this networking issue : https://docs.docker.com/docker-for-mac/networking/#per-container-ip-addressing-is-not-possible
And it seems that this is a Mac os limitation with possible workarounds.

**Comment by PierreBesson** [comment]
@jdubois I think the problems you are having with testcontainer and docker for mac are caused because of this networking issue : https://docs.docker.com/docker-for-mac/networking/#per-container-ip-addressing-is-not-possible
And it seems that this is a Mac os limitation with possible workarounds.

**Comment by jdubois** [comment]
@PierreBesson I spent the evening on this - there are many different possible issues, but the end result for me is that TestContainers is not easy enough for our needs, and that its error messages are not good enough to help people.

We've always focused on having a great "out-of-the-box experience", and this is just not good enough for us - we're going to have tens of thousands of people using this, this must be very smooth and easy.

At the moment my main idea is to accept this Elasticsearch limitation (for Cassandra: we have far less users, and we should be able to have our CassandraUnit hack working), and Mock its calls instead. As this is only used for simple CRUD operations in the entities, that should be very easy to Mock. And if people want integration tests, they need to run the whole thing with Protractor, which is still a very good option.

**Comment by PierreBesson** [comment]
@jdubois OK to delay this after JHipster 5 release but I think your current issue might be due to the combination of docker-compose + testcontainer. Not using docker-compose might give us more control on the testcontainer setup. Anyway no rush here and I'm in vacation for a few days so I will have a look later.

**Comment by jdubois** [comment]
Yes I'm pretty sure Mocks will solve the issue, and will make us use "true"
unit tests, which is normally a good thing.

My issue is indeed with Docker Compose: that's the easiest path for us as
we already have Docker Compose everywhere. Then, maybe that's not a good
solution in the long run as we should move totally to Kubernetes.

Le 19 janv. 2018 12:27 PM, "Pierre Besson" <notifications@github.com> a
écrit :

@jdubois <https://github.com/jdubois> OK to delay this after JHipster 5
release but I think your current issue might be due to the combination of
docker-compose + testcontainer. Not using docker-compose might give us more
control on the testcontainer setup. Anyway no rush here and I'm in vacation
for a few days so I will have a look later.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/7000#issuecomment-358939975>,
or mute the thread

**Comment by jdubois** [comment]
Let me do this tonight with Mocks, that's going to be easy.

**Comment by tchlyah** [comment]
> Couchbase -> they already use TestContainers as I guess @tchlyah didn't know we wanted to avoid it :-)

I'm not a huge fun of unit testing with Docker, as it is heavy, slow to start and error prone. But I had to since there is no other way to test all N1QL queries.
I'm waiting for N1QL compatibility with [CouchbaseMock](https://github.com/couchbase/CouchbaseMock) to migrate.

**Comment by jdubois** [comment]
Closed as I've done with mocks

**Comment by ecostanzi** [comment]
We just published a module for using testcontainers for SQL databases. https://www.npmjs.com/package/generator-jhipster-testcontainers. :)
H2 will still be the default but with `testcontainers` profile you'll run the test using the `prodDatabaseType` database. It's a draft version but it's potentially be extended to non-SQL databases.

**Comment by windbender** [comment]
I realize this issue is closed.  

But I wanted to +1 this.  I do wish I could do all my testing against the same DB I use in production.  In particular, during unit testing it's very helpful for debugging to be able to pause the JVM and still get a command line SQL interface into the DB to understand what is going on.

I think the downsides are that stuff runs more slowly.
