### ISSUE TITLE
ManyToMany with relation name generates add/remove method that do not compile

### ISSUE THREAD

**Issue by agoncal** [jhipster/generator-jhipster#9288]
##### **Overview of the issue**

When in the JDL there is a relation-name on both sides of a  bi-directional `@ManyToMany` the add/remove method code on the entity does not compile.

##### **Motivation for or Use Case**

Reading the [documentation](https://www.jhipster.tech/jdl/#relationshipdeclaration) on the JDL it looks like I can have a relation name on a bi-directional `@ManyToMany`. So it looks like it should work.

##### **Reproduce the error**

I have two entities: `Event` and `Language` (code below). When I have a bi-directional `@ManyToMany` with no relation-name on `Language`, the generated add/remove methods on the `Event` entity work ok:

```
relationship ManyToMany {
    Event{languages(name)} to Language{events}
}

@Entity
public class Event implements Serializable {

    public Event addLanguages(Language language) {
        this.languages.add(language);
        language.getEvents().add(this);
        return this;
    }

    public Event removeLanguages(Language language) {
        this.languages.remove(language);
        language.getEvents().remove(this);
        return this;
    }
}
```

If I add a relation name (here, `slug`) the generated code does not compile (`getEvents(slug)S()`):

```
relationship ManyToMany {
    Event{languages(name)} to Language{events(slug)}
}

@Entity
public class Event implements Serializable {

    public Event addLanguages(Language language) {
        this.languages.add(language);
        language.getEvents(slug)S().add(this);
        return this;
    }

    public Event removeLanguages(Language language) {
        this.languages.remove(language);
        language.getEvents(slug)S().remove(this);
        return this;
    }
}
```

##### **Related issues**

I found these issues that could be related: #8991 and #8447

##### **JHipster Version(s)**

```
cfp@0.0.0 /Users/agoncal/Documents/Code/ConfInABox/Temp/bug/origin
└── generator-jhipster@5.8.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
    "generator-jhipster": {
        "databaseType": "sql",
        "devDatabaseType": "h2Disk",
        "enableHibernateCache": true,
        "enableSwaggerCodegen": false,
        "enableTranslation": true,
        "jhiPrefix": "cfp",
        "languages": ["en", "fr"],
        "messageBroker": false,
        "nativeLanguage": "en",
        "packageName": "com.devoxx.cfp",
        "packageFolder": "com/devoxx/cfp",
        "prodDatabaseType": "postgresql",
        "searchEngine": false,
        "serviceDiscoveryType": false,
        "skipClient": false,
        "skipServer": false,
        "testFrameworks": ["protractor", "gatling"],
        "websocket": false,
        "applicationType": "monolith",
        "authenticationType": "jwt",
        "baseName": "CFP",
        "buildTool": "maven",
        "cacheProvider": "ehcache",
        "clientFramework": "angularX",
        "clientPackageManager": "npm",
        "jhipsterVersion": "5.8.1",
        "skipUserManagement": false,
        "serverPort": "8080",
        "useSass": true,
        "entitySuffix": "",
        "dtoSuffix": "DTO",
        "otherModules": []
    },
    "entities": ["Event", "Language"]
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Event (cfp_event) {
  slug String required,
  name String required,
  description TextBlob,
  website String
}
entity Language (cfp_language) {
  alpha3b String required maxlength(3),
  alpha2 String required maxlength(2),
  name String required
}
relationship ManyToMany {
  Event{languages(name)} to Language{events(slug)}
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

git version 2.20.1

node: v11.10.0

npm: 6.7.0

yarn: 1.13.0

Docker version 18.09.1, build 4c52b90

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
This is fixed already in master (original issue https://github.com/jhipster/generator-jhipster/issues/9202), but we will need a v5 maintenance release.  I opened a PR to fix this in that branch

**Comment by yelhouti** [comment]
@ruddell I'm on master and this is not working :s

**Comment by ruddell** [comment]
@yelhouti Make sure you pulled the latest code, and also installed the `jhipster-core` update in your local `generator-jhipster` (re-run `npm link`)

**Comment by tchlyah** [comment]
@ruddel I've done that and still have the error. Are you sure we are talking about the same problem?

**Comment by ruddell** [comment]
If you are using a release, it's not fixed yet.

If you are using master, make sure you run `npm link generator-jhipster` in your project after generating.  Otherwise, it will use the version from npm which still has the issue.  I just tested again and can't reproduce.

You can validate it's fixed by looking at `.jhipster/Event.json`:

 - Broken

            "otherEntityRelationshipName": "events(slug)",
 - Fixed

            "otherEntityRelationshipName": "events",

**Comment by tchlyah** [comment]
Oh, I'm sorry, I'm the one who was not talking about the same issue...
It seems related to #7944 : in MongoDB relations, `@ManyToMany` relation doesn't generate otherEntity field, which generates non compliling `add` and `remove`methods. I should create an other issue about that.

**Comment by ruddell** [comment]
Closing as this is fixed and released in v5.8.2
